### ISSUE TITLE
Parallelizing particle filters

### ISSUE THREAD

**Issue by juliohm** [JuliaPOMDP/POMDPToolbox.jl#17]
The update of a particle filter is done independently for all particles, this means we can exploit many cores to run the (expensive) generative model in parallel. For instance, in the custom particle filter I am using:

```julia
G(s) = generate_s(pomdp, s, a, rng)
sps = pmap(G, particles)
```

I can start a pull request in the future if you think this may be useful in general.

**Comment by zsunberg** [comment]
Yes, this would probably be useful. I think it would be even more useful to have a thread-parallel version because, for many (most?) applications that use a particle filter, generate_s is very fast and small, so the overhead of running on different processes might be large.

One thing that we should think about is whether the evaluation is deterministic given an rng. If it's not (it would seem like it may not be given that the pmap could execute in a different order), we should think about how to make this clear to the user.

**Comment by juliohm** [comment]
Good point Zach, we should definitely make it clear that parallelism may
inhibit reproduction of results.

Generative models can be quite expensive to run sometimes, let's keep this
possibility in mind :)

-Júlio

**Comment by juliohm** [comment]
I am about to fly to Brazil (on the plane), may I ask you an off-topic
question regarding the peer review of CS238?

Are the papers submitted supposed to involve decision making? I'm reviewing
a paper that apparently only develops a method with neural nets without
clear relation to decision making, how should j proceed? I'll be submitting
the review when I land in my next stop in Miami.

Sorry for the off-topic question, without access to my Stanford email now...

-Júlio

**Comment by juliohm** [comment]
Asked in PIAZZA.

-Júlio

**Comment by juliohm** [comment]
Closing this one too, I think we are aware of the places for improvement. Just a matter of time and need from users to get them implemented.
